### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by deanputney** [brynbellomy/dash-docset-generator#1]
I get this error any time I run `build-dash-docsets` with a fresh install. Looks to be something associated with ES6, [similar issue here](https://github.com/assaf/zombie/issues/909)

`````` /usr/local/lib/node_modules/dash-docset-generator/bin/build-dash-docsets:5
const shell = require('shelljs/global')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3```
``````

**Comment by pirafrank** [comment]
+1
Experienced this with latest node version (0.12.7).

**Comment by jhansen-tt** [comment]
+1 (node 0.12.7)

**Comment by brynbellomy** [comment]
@deanputney @pirafrank @jhansen-tt Sorry for the delay on this — I've been extremely busy at work and don't do a lot of Dash docset generating there :(

I've been using Node.js v4.0.0 and v5.0.0 with this tool, hence the `const` declarations.  But I've removed those and (I think) brought everything back into compliance with Node.js 0.12.x.

New version on npm is `1.0.0` if you want to reinstall and try running it on the examples again.

Feel free to reopen if you have more problems — I'm happy to lend a hand (planet Earth really needs a working generator for arbitrary docsets, IMHO).

**Comment by pirafrank** [comment]
Thank you for your update, man.
